- ip: 10.11.4.51
  rack: 0
  slot: 2
  db:
    - number: 7
      metrics:
        - name: locked_status
          datatype: bool
          metricType: gauge
          help: locked Status
          multiple:
            - offset: 8
              label: tank=1
            - offset: 10
              label: tank=4
        - name: extraction_status
          datatype: bool
          metricType: gauge
          help: Entnahme Status
          multiple:
            - offset: 8.2
              label: tank=3
            - offset: 10.2
              label: tank=4
    - number: 9
      metrics:
        - name: fill_tons
          datatype: real
          metricType: gauge
          help: Ist Tonnen
          multiple:
            - offset: 0
              label: tank=1
            - offset: 12
              label: tank=2
            - offset: 24
              label: tank=3
- name: 'latextank'
  ip: 10.11.4.51
  rack: 0
  slot: 2
  db:
    - number: 1
      metrics:
        - name: operation_automatic_status
          datatype: bool
          metricType: gauge
          help: Automatikbetrieb
          offset: 0
        - name: operation_manual_status
          datatype: bool
          metricType: gauge
          help: Manueller Betrieb
          offset: 0.1
    - number: 3
      metrics:
        - name: fill_level_percent
          datatype: int
          metricType: gauge
          help: Füllstand Prozent
          multiple:
            - offset: 0
              label: tank=1
            - offset: 2
              label: tank=2
            - offset: 4
              label: tank=3
